//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminImage
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    public partial class ImageGallery
    {
        public int ImgId { get; set; }
        public int ImgSize { get; set; }
        public string FileName { get; set; }
        public byte[] ImageData { get; set; }

        [Required(ErrorMessage = "Please Select Image File")]
        public HttpPostedFileBase File { get; set; }
       

    }
}
